# Generated by Django 3.2.5 on 2021-07-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass_manager', '0003_auto_20210718_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcard',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_card', to='pass_manager.folder'),
        ),
    ]
