# Generated by Django 3.2.5 on 2021-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_manager', '0004_alter_passcard_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcard',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
